'''
Q. Problem Statement 1:
Write a function to compute 5/0 and use try/except to catch the exceptions.
'''
def cal_div(div=0,d=0):
    "function to calculate division where div is dividend and d is divisor with default value 0"
    res=div/d
    return res

try:
    q= cal_div(5) # function to compute 5/0
except ZeroDivisionError:
    print("ZerodivisonError:You are trying to do illegal divide by 0")
except:
    print("This is generic excception")
    
